[package]
name = "flux-wasm-builder"
version = "0.7.0"
edition = "2024"

[[bin]]
name = "flux-wasm-builder"
path = "src/bin/main.rs"

[lib]

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["process", "time", "rt", "rt-multi-thread", "macros", "fs", "sync"] }
thiserror = "2.0.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
actix-web = "4"
actix-ws = "0.4.0"
futures-util = "0.3"
mime_guess = "2"
serde_json = "1"
notify-debouncer-mini = "0.7"

[dependencies.include_dir]
version = "0.7"
optional = true

[features]
embed-assets = ["dep:include_dir"]

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
tokio-test = "0.4"
actix-rt = "2"
